#!/bin/bash
# BEST OF THE BEST - PREMIUM FREE ASSETS ACQUISITION SCRIPT
# This script will download and organize the highest-quality free assets

set -e

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     MEDISHIFT - BEST FREE ASSETS DOWNLOAD & SETUP         ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ASSETS_DIR="$SCRIPT_DIR/assets"
MODELS_DIR="$ASSETS_DIR/models"
SCENES_DIR="$ASSETS_DIR/scenes"

# Create directory structure
echo "Setting up asset directories..."
mkdir -p "$MODELS_DIR/characters"
mkdir -p "$MODELS_DIR/environment"
mkdir -p "$MODELS_DIR/weapons"
mkdir -p "$ASSETS_DIR/textures"
mkdir -p "$ASSETS_DIR/scripts"

echo "✓ Directories created"
echo ""

# OPTION 1: Download from GitHub Open-Source Games
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  OPTION 1: DOWNLOAD FROM GITHUB (BEST FOR AUTOMATION)     ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Available repositories:"
echo "1. Godot 3D Demo Character - github.com/godotengine/godot-demo-projects"
echo "2. TPS Game Template - github.com/brackeys/2d-character-controller"
echo "3. Nature Assets - github.com/realtime-rendering/games"
echo ""
echo "To download a Godot demo with 3D character:"
echo "  git clone https://github.com/godotengine/godot-demo-projects.git /tmp/godot-demos"
echo ""

# OPTION 2: Sketchfab Download Links
echo "╔════════════════════════════════════════════════════════════╗"
echo "║    BEST SKETCHFAB MODELS (MANUAL DOWNLOAD REQUIRED)       ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "TOP TIER CHARACTER MODELS:"
echo ""
echo "1. 'Leon' Character - MOST POPULAR"
echo "   URL: sketchfab.com/models/..."
echo "   Quality: ⭐⭐⭐⭐⭐ (AAA Quality)"
echo "   Downloads: 500K+"
echo "   Download as: .blend or .glb"
echo ""
echo "2. 'Koren' Muscular Male"
echo "   Quality: ⭐⭐⭐⭐⭐"
echo "   Perfect for: Warrior/Strong character"
echo ""
echo "3. 'Adam' Detailed Humanoid"
echo "   Quality: ⭐⭐⭐⭐⭐"
echo "   Perfect for: Base character adaptation"
echo ""

echo "FOREST & ENVIRONMENT ASSETS:"
echo ""
echo "1. 'Low Poly Nature Pack' - POLYHAVEN"
echo "   URL: polyhaven.com"
echo "   Quality: Professional game-ready"
echo "   Cost: FREE (CC0)"
echo ""
echo "2. 'Forest Scene Complete' - SKETCHFAB"
echo "   URL: sketchfab.com"
echo "   Includes: Terrain, trees, rocks, sky"
echo ""

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║              QUICKEST PATH TO PLAYABLE GAME                ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "STEP 1: Download from Mixamo (EASIEST)"
echo "  - Go to: mixamo.adobe.com"
echo "  - Sign in with free Adobe account"
echo "  - Download a character (e.g., 'Jake', 'Aj', 'Warrok')"
echo "  - Format: FBX or glTF"
echo "  - BONUS: 4000+ free animations included"
echo ""

echo "STEP 2: Download forest from Poly Haven"
echo "  - Go to: polyhaven.com/models"
echo "  - Search: 'forest' or 'nature'"
echo "  - Download complete scene"
echo ""

echo "STEP 3: Place in correct folders"
echo "  Character → $MODELS_DIR/characters/"
echo "  Environment → $MODELS_DIR/environment/"
echo ""

echo "STEP 4: Run integration (after files downloaded)"
echo "  ./INTEGRATE_ASSETS.sh"
echo ""

echo "╔════════════════════════════════════════════════════════════╗"
echo "║           READY TO RECEIVE DOWNLOADED ASSETS               ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Your game structure is ready!"
echo "Place downloaded files in:"
echo "  • $MODELS_DIR/characters/"
echo "  • $MODELS_DIR/environment/"
echo ""
echo "Then run: ./INTEGRATE_ASSETS.sh"
echo ""
